export const children = [
    {
      id: 1,
      name: "ひらおか たく",
      age: 9,
      photo: "/placeholder.svg?height=100&width=100",
      interests: ["アート", "読書"],
      behavioralPatterns: ["協力的", "好奇心旺盛"],
      learningProgress: {
        math: 85,
        reading: 92,
        science: 78,
      },
      emotion: "😃",
    },
    {
      id: 2,
      name: "おおがね たかふみ",
      age: 9,
      photo: "/placeholder.svg?height=100&width=100",
      interests: ["スポーツ", "科学"],
      behavioralPatterns: ["活発", "集中力が散漫"],
      learningProgress: {
        math: 90,
        reading: 80,
        science: 95,
      },
      emotion: "🥳",
    },
    {
      id: 3,
      name: "はやし たいき",
      age: 6,
      photo: "/placeholder.svg?height=100&width=100",
      interests: ["スポーツ", "科学"],
      behavioralPatterns: ["活発", "集中力が散漫"],
      learningProgress: {
        math: 90,
        reading: 80,
        science: 95,
      },
      emotion: "😡",
    },
    {
      id: 4,
      name: "ほりぐち さくら",
      age: 10,
      photo: "/placeholder.svg?height=100&width=100",
      interests: ["スポーツ", "科学"],
      behavioralPatterns: ["活発", "集中力が散漫"],
      learningProgress: {
        math: 90,
        reading: 80,
        science: 95,
      },
      emotion: "😂",
    },
    {
      id: 5,
      name: "さたけ なおあき",
      age: 12,
      photo: "/placeholder.svg?height=100&width=100",
      interests: ["スポーツ", "科学"],
      behavioralPatterns: ["活発", "集中力が散漫"],
      learningProgress: {
        math: 90,
        reading: 80,
        science: 95,
      },
      emotion: "🤔",
    },
    {
      id: 6,
      name: "いしはら ゆうすけ",
      age: 12,
      photo: "/placeholder.svg?height=100&width=100",
      interests: ["スポーツ", "科学"],
      behavioralPatterns: ["活発", "集中力が散漫"],
      learningProgress: {
        math: 90,
        reading: 80,
        science: 95,
      },
      emotion: "💤",
    },
  ]