export const children = [
    {
      id: 1,
      name: "たくくん",
      age: 9,
      photo: "/placeholder.svg?height=100&width=100",
      interests: ["アート", "読書"],
      behavioralPatterns: ["協力的", "好奇心旺盛"],
      learningProgress: {
        math: 85,
        reading: 92,
        science: 78,
      },
      emotion: "happy",
    },
    {
      id: 2,
      name: "たかふみくん",
      age: 9,
      photo: "/placeholder.svg?height=100&width=100",
      interests: ["スポーツ", "科学"],
      behavioralPatterns: ["活発", "集中力が散漫"],
      learningProgress: {
        math: 90,
        reading: 80,
        science: 95,
      },
      emotion: "excited",
    },
    {
      id: 3,
      name: "たいきくん",
      age: 6,
      photo: "/placeholder.svg?height=100&width=100",
      interests: ["スポーツ", "科学"],
      behavioralPatterns: ["活発", "集中力が散漫"],
      learningProgress: {
        math: 90,
        reading: 80,
        science: 95,
      },
      emotion: "angry",
    },
    {
      id: 4,
      name: "さくらちゃん",
      age: 10,
      photo: "/placeholder.svg?height=100&width=100",
      interests: ["スポーツ", "科学"],
      behavioralPatterns: ["活発", "集中力が散漫"],
      learningProgress: {
        math: 90,
        reading: 80,
        science: 95,
      },
      emotion: "calm",
    },
    {
      id: 5,
      name: "なおあきくん",
      age: 12,
      photo: "/placeholder.svg?height=100&width=100",
      interests: ["スポーツ", "科学"],
      behavioralPatterns: ["活発", "集中力が散漫"],
      learningProgress: {
        math: 90,
        reading: 80,
        science: 95,
      },
      emotion: "sad",
    },
  ]